syncdb fails after previous commit.
This commit fixes the error.

C:\learningdjango\mysite [master]> python manage.py syncdb
CommandError: One or more models did not validate:
admin.logentry: 'content_type' has a relation with model <class
'django.contrib.contenttypes.models.ContentType'>, which has either not
been installed or is abstract.
auth.permission: 'content_type' has a relation with model <class
'django.contrib.contenttypes.models.ContentType'>, which has either not
been installed or is abstract.